### ISSUE TITLE
[EPIC] UI design for web app as presentation

### ISSUE THREAD

**Issue by shorn-gnosis** [aboutcircles/circles-data-app#10]
### Scenario:
Our aim is to build a useful set of interactive tools to educate users on how the Circles protocol works. The tools will be integrated into a web app that can also be used as a presentation device at events.

### To do:
- [ ] #12

The app should have the following base elements:
- [ ] navigation to enable the user to view the pages and easily navigate between them
- [ ] relevant form controls for the charts for each page view (d3, sankey, etc)
- [ ] on-brand design - palette and fonts etc (ref: aboutcircles.com and style guide: https://www.figma.com/file/f1o3ZNZpREzHPJNbMnEsDG/Circles-Brand-Reboot-(Copy)?type=design&node-id=1344-128&mode=design
- [ ] more to follow...

![Image](https://github.com/aboutcircles/path-visualizer/assets/141832818/1fd9faf7-5c56-43d6-8243-7b25a0ce335b)
